import { Column, Entity, PrimaryGeneratedColumn } from "typeorm";

@Entity()
export class patient{
@PrimaryGeneratedColumn()
id:number
@Column()
aadhar:string
@Column()
name:string
@Column()
dob:Date
@Column()
sex:string
@Column()
maritalStatus:string
@Column()
fatherName:string
@Column()
husbandName:string
@Column()
motherName:string
@Column()
wifeName:string
@Column()
ReferencedByName:string
@Column()
ReferenceByMobile:string
@Column()
consentFormImage:string
@Column()
Address:string
@Column()
HouseNo:string
@Column()
buildingorMohalla:string
@Column()
village:string
@Column()
city:string
@Column()
state:string
@Column()
country:string
@Column()
patientOccupation:string
@Column()
patientMobile:string
@Column()
email:string
@Column()
emergencyMobile:string
@Column()
isActive:number
@Column({type:'date',nullable:true,default:null})
CreatedAt:Date
@Column()
CreatedBy:number
@Column({type:'date',nullable:true,default:null})
UpdatedAt:Date
@Column()
UpdatedBy:number


}